imports:
    - { resource: config_dev.yml }

parameters:
    hangman.word_length: 3

doctrine:
    dbal:
        dbname:   hangman_test

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
