parameters:
    database_driver:     pdo_mysql
    database_host:       localhost
    database_port:       ~
    database_name:       hangman
    database_user:       root
    database_password:   ~

    mailer_transport:    smtp
    mailer_host:         localhost
    mailer_user:         ~
    mailer_password:     ~

    locale:              en
    secret:              ThisTokenIsNotSoSecretChangeIt

    hangman.max_games:   5
    hangman.word_length: 8
