_homepage:
    pattern:  /
    defaults: { _controller: SensioHangmanBundle:Player:registration }

login:
    pattern:  /login
    defaults: { _controller: SensioHangmanBundle:Player:login }

logout:
    pattern:  /logout

login_check:
    pattern:      /auth
    requirements: { _method: POST }

SensioHangmanBundle:
    resource: "@SensioHangmanBundle/Controller"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /esi