jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Sensio\Bundle\HangmanBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 3000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        players:
            entity: { class: SensioHangmanBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        game:
            pattern:                 ^/
            anonymous:               true
            switch_user:             true
            form_login:    
                login_path:          /login
                check_path:          /auth
                default_target_path: /game/
            logout:
                path:                /logout
                target:              /login

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/esi, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/(registration|login)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
