<?php

namespace Sensio\Bundle\HangmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getMostRecentUsers($limit)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->where('u.isActive = :active')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults($limit)
            ->setParameter('active', true)
            ->getQuery()
        ;

        return $q->getResult();
    }
}